<div class="post-content">
				<h1 data-fontsize="54" style="--fontSize: 54; line-height: 1.16;" data-lineheight="62.64px" class="fusion-responsive-typography-calculated"><span style="font-weight: 400;">Phoenix Park Privacy Policy</span></h1>
<p><span style="font-weight: 400;">We understand that the privacy of your personal and business information that you provided to us as an employee, contractor, realtor, broker, or purchaser is very important to you, and we take protecting your information very seriously at all Phoenix Park entities.</span></p>
<p><span style="font-weight: 400;">We use the data gathered only to provide you with more information about our quality residential products and commercial construction services. This information will not be sold or distributed to any unaffiliated third parties without your prior consent.</span></p>
<p><span style="font-weight: 400;">Digital Information We Automatically Collect</span></p>
<p><span style="font-weight: 400;">Our digital platforms log your IP address in order to help diagnose problems with our servers, administer our websites, and track online usage statistics. Your IP address may vary each time you visit, or it may be the same, depending on whether you access our site through an always-on type of internet connection or mobile device. If you reached our site by clicking on a link or advertisement on another site, then we also log that information. This helps us maximize our Internet exposure, and it helps us understand our users’ interests. All of this information is collected and used only in the aggregate; that is, it is entered into our database, where we can use it to generate overall reports on our visitors, but not individual reports that identify you personally.</span></p>
<p><span style="font-weight: 400;">We also place a small text file known as a “cookie” on your computer or mobile device. A cookie may contain information that allows us to track your path through our sites and to determine whether you have visited us before. Unless you register with us, however, a cookie contains no personally identifiable information that would allow us to identify you. Cookies cannot be used to read data off of your hard drive, and cannot retrieve information from any other cookies created by other Web sites. We use cookies to help us understand how visitors use our sites and to help us to improve our digital presence and user experience. You may refuse to accept a cookie from us by following the procedures specific to your web browser. Although you may do so, you may find that your browser reacts strangely when visiting not only our websites but other online sites as well. Since cookies don’t provide us with any information from which we can identify you, we suggest you allow us to place one on your computer so that your digital experience while home shopping is smoother while gathering information on our varied housing communities and construction projects.</span></p>
<p><span style="font-weight: 400;">We may use web beacons on our site or other sites and may permit third parties to place them on our site to monitor the effectiveness of advertising or for other legitimate purposes. A web beacon is a small, graphic image on a web page, web-based document, or in an e-mail message that is designed to allow the site owner or a third party to monitor who is visiting a site. Web beacons are often invisible to the user because they are typically very small (only 1-by-1 pixel) and the same color as the background of the Web page, document, or e-mail message. Web beacons are represented as HTML IMG tags on the webpage; users can click on “view profiles” of the webpage to see whether the page is using a web beacon. Web beacons collect the IP address of the computer that the beacon is sent to, the URL of the page the web beacon comes from and the time it was viewed. Web beacons can also be linked to personal information, for example, advertising networks use web bugs to add information to a personal profile of what sites a person is visiting and to determine what banner ads to display based on the profile, and to provide an independent accounting of how many people have visited a particular website or landing page. Web bugs are also used to gather statistics about web browser usage at different places on the internet.</span></p>
<p><span style="font-weight: 400;">We may use third-party ad servers (or ad networks) to deliver ads to you on our behalf. These third-party ad servers may collect and use non-personally identifiable information about your visits to our site in order to present advertisements that may be of interest to you.</span></p>
<p><span style="font-weight: 400;">Unsubscribing from Emails</span></p>
<p><span style="font-weight: 400;">If you are currently receiving emails from any of our Phoenix Park entities, and wish to be removed from our mailing list, simply open the email we sent to you and click on the “unsubscribe” link.&nbsp;</span></p>
<p><span style="font-weight: 400;">Unfollowing from Social Media</span></p>
<p><span style="font-weight: 400;">If you no longer wish to view and engage with our social media channels simply “unfollow” or “unsubscribe” to all of our social media channels and refrain from interacting, commenting, sharing, and clicking on our content. Clear your browsing history from search engines, video hosting platforms, and remove us from any bookmarks, favorites, and saved links.</span></p>
<p><span style="font-weight: 400;">Statement of Forward-looking Information</span></p>
<p><span style="font-weight: 400;">Certain information included herein and in other Company reports, SEC filings, verbal or written statements, and presentations are forward-looking within the meaning of the Private Securities Litigation Reform Act of 1995, including, but not limited to, information related to anticipated operating results, financial resources, changes in revenues, changes in profitability, changes in margins, changes in accounting treatment, interest expense, land-related write-downs, effects of home buyer cancellations, growth and expansion, anticipated income to be realized from our investments in unconsolidated entities, the ability to acquire land, the ability to gain approvals and to open new communities, the ability to sell homes and properties, the ability to deliver homes from backlog, the ability to secure materials and subcontractors, the ability to produce the liquidity and capital necessary to expand and take advantage of opportunities in the future, industry trends, and stock market valuations. Such forward-looking information involves important risks and uncertainties that could significantly affect actual results and cause them to differ materially from expectations expressed herein and in other company reports, SEC filings, statements, and presentations. These risks and uncertainties include local, regional and national economic conditions, the demand for homes, domestic and international political events, uncertainties created by terrorist attacks, the effects of governmental regulation, the competitive environment in which the company operates, fluctuations in interest rates, changes in home prices, the availability and cost of land for future growth, the availability of capital, uncertainties, and fluctuations in capital and securities markets, changes in tax laws and their interpretation, legal proceedings, the availability of adequate insurance at a reasonable cost, the ability of customers to finance the purchase of homes, the availability and cost of labor and materials, and weather conditions.</span></p>
<h2 data-fontsize="28" style="--fontSize: 28; line-height: 1.2; --minFontSize: 28;" data-lineheight="33.6px" class="fusion-responsive-typography-calculated"><span style="font-weight: 400;">Real Estate Developments</span></h2>
<p><span style="font-weight: 400;">ORAL REPRESENTATIONS CANNOT BE RELIED UPON AS CORRECTLY STATING REPRESENTATIONS OF THE DEVELOPER. FOR CORRECT REPRESENTATIONS, MAKE REFERENCE TO THIS BROCHURE AND TO THE DOCUMENTS REQUIRED BY SECTION 718.503, FLORIDA STATUTES, TO BE FURNISHED BY A DEVELOPER TO A BUYER OR LESSEE. All dimensions are approximate and subject to normal construction variances and tolerances. Plan and dimensions may contain variations from floor to floor. There are two generally accepted methods for calculating the square footage of the Unit. The “Parametrical Method” is based on the description of the boundaries of the Unit, as set forth in the Declaration of Condominium, and only includes the airspace within a Unit. The “Architectural Method”&nbsp; measures a Unit to the outside finished surface of exterior walls and to the centerline of interior demising walls and includes portions of the Common Elements of the Condominium. The square footage derived using the Architectural Method is set forth above and is included in sales materials to allow a prospective buyer to compare the square footage of the Units with units in other condominium projects that utilize the Architectural Method. The Parametrical Method is used in the legal documents for Harbor Island Beach Club, A Condominium (Phase l, II, lll, lV, V). All artist’s or architectural renderings, sketches, graphic materials and photos depicted or otherwise described herein are proposed and conceptual only and are based upon preliminary development plans, which are subject to change. In no event will the presence of any furniture, furnishings, equipment, decorations, or landscaping in any Unit (or any Common Elements appurtenant thereto) or in any advertisements imply or represent that any Unit or Common Element will contain such furniture, furnishings, equipment, decorations or landscaping upon delivery of the Unit. Any furniture or other interior décor is for informational purposes only and will not be included in the sale of any unit Within Harbor Island Beach Club, A Condominium (Phase l, II, lll, lV, V). This is not an offering in any state in which registration is required but in which registration requirements have not yet been met. This advertisement is not an offering. It is a solicitation of interest in the advertised property. No offering of the advertised units can be made and no deposits can be accepted, or reservations, binding or non-binding, can be made in New York until an offering plan is filed with the New York State Department of Law.</span></p>
<p><span style="font-weight: 400;">No view is promised. Views may also be altered by subsequent development, construction, and landscaping growth. Square footage/acreage shown is only an estimate and actual square footage/acreage will differ. The buyer should rely on his or her own evaluation of the usable area. Completion and/or move-in dates are estimated. Prices, plans, and terms are effective on the date of publication and subject to change without notice. Depictions of homes or other features are artist conceptions. Hardscape, landscape, and other items shown may be decorator suggestions that are not included in the purchase price and availability may vary.&nbsp;</span></p>
<h3 data-fontsize="32" style="--fontSize: 32; line-height: 1.3;" data-lineheight="41.6px" class="fusion-responsive-typography-calculated"><span style="font-weight: 400;">Phoenix Park Accessibility Policy</span></h3>
<p><span style="font-weight: 400;">All entities of Phoenix Park are committed to providing accessibility to its electronic media to persons with disabilities. If you have difficulty accessing content on our websites or notice any accessibility problems, please contact <a href="mailto:info@buildwithphoenixpark.com">info@buildwithphoenixpark.com</a> and specify the nature of the accessibility issue and whether you are using any assistive technology. One of our representatives will attempt to assist you with any accessibility concerns.&nbsp;&nbsp;</span></p>
<p><span style="font-weight: 400;">For individuals who are visually impaired, t</span><span style="font-weight: 400;">here are several things you can do to adjust your web browser and make your online experience more accessible. If you have trouble seeing web pages, please consider these suggestions from the <a href="https://www.ssa.gov/accessibility/">US Social Security Administration</a> to optimize your system and browser and improve your online experience.</span></p>
<p><span style="font-weight: 400;">Contact Us <a href="mailto:info@buildwithphoenixpark.com">info@buildwithphoenixpark.com</a></span></p>
<p>&nbsp;</p>
<h4 data-fontsize="28" style="--fontSize: 28; line-height: 1.36; --minFontSize: 28;" data-lineheight="38.08px" class="fusion-responsive-typography-calculated"><span style="font-weight: 400;">Phoenix Park COVID-19 Policy</span></h4>
<p><span style="font-weight: 400;">All Phoenix Park entities are concerned about the safety and health of our employees, contractors, real estate professionals, and clients. We continue to monitor the CDC, National Association of Realtors, and Florida Government websites for updated information and guidance for visitor safety at our locations.&nbsp;</span></p>
<p><span style="font-weight: 400;">We have provided no-touch services that reduce physical contact including virtual tours, video, and webinars to showcase our products. Purchasing solutions include DocuSign, wire transfer, and drive-up services.</span></p>
<p><span style="font-weight: 400;">All physical offices and sales centers are sanitized regularly, are equipped with hand sanitizer, hand washing stations, and we require face masks at all locations.</span></p>
<p><span style="font-weight: 400;">Team members who are sick and at-risk are instructed to stay home. We have requested that our contractors conduct wellness checks and instruct their employees that are sick or at risk for COVID to refrain from visiting our job sites. </span></p>
<p><span style="font-weight: 400;">We follow the <a href="https://www.nar.realtor/">National Association of Realtors</a> Coronavirus Guide For Realtors to provide a safe and healthy experience during the current pandemic.</span></p>
<p><a href="https://www.nar.realtor/coronavirus-a-guide-for-realtors" target="_blank" rel="noopener"><img decoding="async" fetchpriority="high" class="aligncenter wp-image-934 size-full" src="https://buildwithphoenixpark.com/wp-content/uploads/2021/03/National-Associaltion-of-Realtors-logo.png" alt="National Association of Realtors logo" width="498" height="180" srcset="https://buildwithphoenixpark.com/wp-content/uploads/2021/03/National-Associaltion-of-Realtors-logo-200x72.png 200w, https://buildwithphoenixpark.com/wp-content/uploads/2021/03/National-Associaltion-of-Realtors-logo-300x108.png 300w, https://buildwithphoenixpark.com/wp-content/uploads/2021/03/National-Associaltion-of-Realtors-logo-400x145.png 400w, https://buildwithphoenixpark.com/wp-content/uploads/2021/03/National-Associaltion-of-Realtors-logo.png 498w" sizes="(max-width: 498px) 100vw, 498px"></a></p>
<p><span style="font-weight: 400;">Updated March 1, 2021</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Phoenix Park Entities <a href="https://www.hud.gov/sites/documents/FHEO_Booklet_Eng.pdf">Equal Housing Opportunity</a> Statement</span></p>
<p><span style="font-weight: 400;">We are pledged to the letter and spirit of U.S. policy for the achievement of equal housing opportunity throughout the Nation. We encourage and support an affirmative advertising and marketing program in which there are no barriers to obtaining housing because of race, color, religion, sex, handicap, familial status, or national origin.&nbsp;</span></p>
<p><span style="font-weight: 400;">Phoenix Park Entities Fair Housing Advertising Publisher Statement</span></p>
<p><span style="font-weight: 400;">All real estate advertised herein is subject to the Federal Fair Housing Act, which makes it illegal to advertise “any preference, limitation, or discrimination because of race, color, religion, sex, handicap, familial status, or national origin, or intention to make any such preference, limitation, or discrimination.” We will not knowingly accept any advertising for real estate which is in violation of the law. All persons are hereby informed that all dwellings advertised are available on an equal opportunity basis.</span></p>
<p>&nbsp;</p>
<p><a href="https://www.hud.gov/fairhousing" target="_blank" rel="noopener"><img decoding="async" class="aligncenter wp-image-935 size-full" src="https://buildwithphoenixpark.com/wp-content/uploads/2021/03/equal-housing-opportunity-logo-blue.png" alt="equal housing opportunity logo" width="225" height="225" srcset="https://buildwithphoenixpark.com/wp-content/uploads/2021/03/equal-housing-opportunity-logo-blue-66x66.png 66w, https://buildwithphoenixpark.com/wp-content/uploads/2021/03/equal-housing-opportunity-logo-blue-150x150.png 150w, https://buildwithphoenixpark.com/wp-content/uploads/2021/03/equal-housing-opportunity-logo-blue-200x200.png 200w, https://buildwithphoenixpark.com/wp-content/uploads/2021/03/equal-housing-opportunity-logo-blue.png 225w" sizes="(max-width: 225px) 100vw, 225px"></a></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
							</div>