<footer id="colophon" class="site-footer bg-primary py-12" role="contentinfo">
	<?php do_action( 'tailpress_footer' ); ?>

	<div class="container mx-auto text-center text-white">
		<div class="flex items-center justify-center gap-x-4 text-2xl mb-6 hidden">
			<a href="https://www.facebook.com/HarborIslandBchClub" target="_blank"><i class="fa-brands fa-facebook"></i></a>
			<a href="https://www.instagram.com/harborislandbeachclub/" target="_blank"><i class="fa-brands fa-instagram"></i></a>
			<a href="https://www.linkedin.com/company/harbor-island-beach-club/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
			<a href="https://twitter.com/HarborIslandBch" target="_blank"><i class="fa-brands fa-twitter"></i></a>
			<a href="https://www.youtube.com/channel/UCi5sOTWjsq-Q-DY0PwNxTNQ" target="_blank"><i class="fa-brands fa-youtube"></i></a>
		</div>

		<p class="mb-6"><a href="mailto:sales@baselinepg.com" class="!no-underline !text-white">sales@baselinepg.com </a> | All Rights Reserved | <a href="#" class="!no-underline !text-white" id="modal-button" data-target-modal="privacy-policy">Privacy Policy</a><!-- | <a href="#" id="modal-button" data-target-modal="disclaimer">Disclaimer</a>--></p>

		<p class="mb-6">ORAL REPRESENTATIONS CANNOT BE RELIED UPON AS CORRECTLY STATING REPRESENTATIONS OF THE DEVELOPER. FOR CORRECT REPRESENTATIONS, MAKE REFERENCE TO THIS BROCHURE AND TO THE DOCUMENTS REQUIRED BY SECTION 718.503, FLORIDA STATUTES, TO BE FURNISHED BY A DEVELOPER TO A BUYER OR LESSEE.</p>

		<img src="<?= get_template_directory_uri(); ?>/images/realtor.svg" alt="" class="mx-auto w-[40px] mb-6"/>

		<p class="mb-6 text-xs text-justify">THIS INFORMATIONAL WEBSITE AND ANY INFORMATION OR MATERIALS PROVIDED HEREIN IS NOT INTENDED TO BE AN OFFERING TO RESIDENTS IN ANY JURISDICTION OUTSIDE OF FLORIDA. VOID WHERE PRIOR REGISTRATION IS REQUIRED OR OTHERWISE PROHIBITED BY LAW</p>

		<p class="mb-6 text-xs text-justify">THE INFORMATION AND MATERIALS DISPLAYED HEREIN ARE SOLELY INTENDED TO PROVIDE GENERAL INFORMATION ABOUT PROPOSED PLANS OF THE DEVELOPER WITH RESPECT TO THE PROPOSED CONDOMINIUM. NEITHER THE INFORMATION AND MATERIALS DESCRIBED HEREIN, NOR ANY COMMUNICATION MADE OR GIVEN IN CONNECTION WITH ANY OF THE FOREGOING, MAY BE DEEMED TO CONSTITUTE ANY REPRESENTATION OR WARRANTY OR MAY OTHERWISE BE RELIED UPON BY ANY PERSON OR ENTITY FOR ANY REASON WHATSOEVER. ARTISTS’ RENDERINGS, PRICES, PHOTOGRAPHS AND AMENITIES ARE BASED ON THE CURRENT DEVELOPMENT PLANS AND ARE SUBJECT TO CHANGE WITHOUT NOTICE. PLEASE REFER TO HARBOR ISLAND BEACH CLUB II CONDOMINIUM APPROVED SURVEY, FLOOR AND PLOT PLANS AND CONDOMINIUM DOCUMENTS FOR SPECIFIC INFORMATION.</p>

		<p class="mb-6 text-xs text-justify">UNTIL THE FINAL COMPLETION OF THE CONDOMINIUM, THE DEVELOPER RESERVES THE ABSOLUTE RIGHT TO CONSTRUCT ADDITIONAL FACILITIES AND IMPROVEMENTS WITHIN THE CONDOMINIUM AND, FROM TIME-TO-TIME IN ITS SOLE AND ABSOLUTE DISCRETION, REMOVE, ADD, MODIFY, AND CHANGE THE BOUNDARIES, FACILITIES, IMPROVEMENTS, AND THE ACTIVITIES/SERVICES DESCRIBED HEREIN. ALL IMPROVEMENTS AND AMENITIES ARE SUBJECT TO CHANGE WITHOUT PRIOR NOTICE. NO GUARANTEES OR REPRESENTATIONS WHATSOEVER ARE MADE THAT THE FEATURES, AMENITIES, AND FACILITIES, AND EXISTING OR FUTURE VIEWS OF THE PROJECT AND SURROUNDING AREAS, DEPICTED BY ANY SUCH ARTISTS’ RENDERINGS OR OTHERWISE DESCRIBED HEREIN, WILL BE PROVIDED, OR IF PROVIDED, WILL BE OF THE SAME TYPE, COLOR, SIZE, LOCATION, OR NATURE AS DEPICTED OR DESCRIBED HEREIN. THE FLOORPLAN DESIGNS, FIXTURES, FURNISHINGS, FINISHES, AND DÉCOR DEPICTED INCLUDE FABRICATIONS, INSTALLATIONS, AND SELECTIONS WHICH MAY NOT BE INCLUDED WITH THE PURCHASE OF A UNIT. THERE MAY (OR MAY NOT) BE FINISHES AVAILABLE TO PURCHASE AT AN ADDITIONAL COST AS AN UPGRADE TO YOUR UNIT. CONSULT THE PROSPECTUS FOR THE CONDOMINIUM FOR INFORMATION REGARDING THE UNIT DESIGNS. SKETCHES, RENDERINGS, OR PHOTOGRAPHS DEPICTING LIFESTYLE, AMENITIES, CLUB SERVICES, FINISHES, DESIGNS, MATERIALS, FURNISHINGS, PLANS OR SPECIFICATIONS CONTAINED IN THIS BROCHURE AND SITE ARE PROPOSED ONLY, AND THE DEVELOPER RESERVES THE RIGHT TO MODIFY, REVISE, OR WITHDRAW ANY OR ALL IN DEVELOPER’S SOLE DISCRETION WITHOUT PRIOR NOTICE. DIMENSIONS AND SQUARE FOOTAGE ARE APPROXIMATE AND MAY VARY DEPENDING ON HOW MEASURED AND BASED UPON ACTUAL CONSTRUCTION. ALSO, LOCATIONS AND LAYOUTS OF WINDOWS, DOORS, CLOSETS, PLUMBING FIXTURES, STRUCTURAL FEATURES, AND ARCHITECTURAL DESIGN ELEMENTS MAY VARY FROM CONCEPT TO ACTUAL CONSTRUCTION. ALL DEPICTIONS OF APPLIANCES, PLUMBING FIXTURES, COUNTERS, COUNTERTOPS, CABINETS, SOFFITS, FLOOR COVERINGS AND OTHER MATTERS OF DESIGN AND DÉCOR DETAIL ARE CONCEPTUAL AND ARE NOT NECESSARILY INCLUDED IN EACH UNIT AND SUCH DRAWINGS, IMAGES, AND DEPICTIONS SHOWN SHOULD NOT BE RELIED UPON AS REPRESENTATIONS, EXPRESS OR IMPLIED, OF THE FINAL DETAIL OF THE CONDOMINIUM OR ANY UNIT. ALL IMPROVEMENTS, DESIGNS AND CONSTRUCTION ARE SUBJECT TO FIRST OBTAINING THE APPROPRIATE FEDERAL, STATE, AND LOCAL PERMITS AND APPROVALS FOR SAME WHICH MAY REQUIRE THE DEVELOPER TO ALTER ANY DESIGN, FLOOR PLAN, OR LAYOUT DEPICTED.</p>

		<p class="mb-6 text-xs text-justify">THE PROSPECTUS AND MARKETING OF THE DEVELOPER IS NOT AN OFFERING OF SECURITIES. NO STATEMENTS OR REPRESENTATIONS MADE BY DEVELOPER, OR ANY OF ITS AGENTS, EMPLOYEES, OR REPRESENTATIVES WITH RESPECT TO ANY POTENTIAL FOR FUTURE PROFIT, FUTURE APPRECIATION IN VALUE, INVESTMENT OPPORTUNITY POTENTIAL, RENTAL INCOME POTENTIAL, OR OTHER BENEFITS TO BE DERIVED FROM OWNERSHIP OF A UNIT SHOULD BE RELIED UPON IN YOUR DECISION TO PURCHASE A UNIT. THE DEVELOPER, AND ITS RESPECTIVE AGENTS, EMPLOYEES, AND REPRESENTATIVES ARE ALSO NOT TAX ADVISORS AND STATEMENT(S) THAT MAY BE OR MAY HAVE BEEN MADE WITH RESPECT TO TAX BENEFITS OF OWNERSHIP SHOULD NOT BE RELIED UPON IN YOUR DECISION TO PURCHASE A UNIT. ALL REPRESENTATIONS CANNOT BE RELIED UPON AS CORRECTLY STATING THE REPRESENTATIONS OF BSLN-FL-1 HIBC CONDO LLC OR ITS AFFILIATES. NEARBY SERVICES AND ATTRACTIONS, INCLUDING BUT NOT LIMITED TO CLUB AMENITIES, ARE NOT CONTROLLED BY DEVELOPER AND MAY NOT BE AVAILABLE FOR USE UPON COMPLETION OF THE CONDOMINIUM. THERE IS NO GUARANTEE THAT ANY PROPOSED CONDOMINIUM PROPERTY, CLUB AMENITIES, FITNESS FACILITIES, OR ADJACENT IMPROVEMENTS WILL BE AVAILABLE AS DEPICTED OR AT ALL UPON, OR FOLLOWING, THE COMPLETION OF THE CONDOMINIUM. NO REAL ESTATE BROKER OR SALES AGENT (WHETHER ENGAGED BY DEVELOPER OR NOT) IS AUTHORIZED TO MAKE ANY REPRESENTATIONS OR OTHER STATEMENTS (VERBAL OR WRITTEN) REGARDING THE CONDOMINIUM. CONSULT THE PROSPECTUS OF DEVELOPER TO UNDERSTAND THE PROPOSED CONDOMINIUM PROPERTY, PROPOSED BUDGET, TERMS, CONDITIONS, SPECIFICATIONS, FEES, UNIT DIMENSIONS, SITE PLANS, AND TO LEARN WHAT IS INCLUDED WITH PURCHASE AND BY PAYMENT OF REGULAR ASSESSMENTS. THE PROJECT GRAPHICS, RENDERINGS, PHOTOGRAPHS, AND TEXT PROVIDED HEREIN ARE COPYRIGHTED WORKS OWNED BY THE DEVELOPER UNLESS OTHERWISE CREDITED.</p>
	</div>
</footer>

<div id="privacy-policy-modal" class="modal" style="display: none;">
    <div class="modal-content">
        <i class="fa-regular fa-xmark fa-xl close"></i>
        <div class="modal-body">
            <div class="entry-content p-8">
				<?php get_template_part( 'template-parts/privacy-policy' ); ?>
            </div>
        </div>
    </div>
</div>

<div id="disclaimer-modal" class="modal" style="display: none;">
    <div class="modal-content">
        <i class="fa-solid fa-xmark close"></i>
        <div class="modal-body">
            <div class="entry-content p-8">
				<?php get_template_part( 'template-parts/disclaimer' ); ?>
            </div>
        </div>
    </div>
</div>